### ISSUE TITLE
[BUG] test 2

### ISSUE THREAD

**Issue by slashpai** [slashpai/gh-test-repo#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

test

### Did you expect to see something different?

test

### Environment

```markdown
- Prometheus Operator version (please provide operator version and not kube-prometheus/helm chart version):
- Kubernetes Version:
- Kubernetes Cluster Type:
```

### Manifests

```YAML
apiVersion: v1
kind: Pod
metadata:
  labels:
     app: example
```
